# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5befa6f5a4c33136cea73b6c96e327bd35636262b9d85ac5457a97ec8cbc27d8b0686b6cae100cee20abfa7469ef300d9fcb2a6a41e7a394c517f17621f17ca8

test:
  secret_key_base: 788357a8afe39e3e53d47c192d78a34e812346d210c3413cefc0cfeb45b3ca32ec894efd9393c27ec962954bea11ecc19cb59eabdcd5dd5c316bb7f004b15407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
